--- # Target and task playbook

- hosts: demo
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Installing web server...
      action: yum name=httpd state=present
      action: service name=httpd state=started

