--- # vars....

- hosts: demo
  user: ansible
  become: yes
  connection: ssh

  vars:
    pkgname: tree

  tasks:
    - name: Installing {{pkgname}} on nodes...

      action: yum name='{{pkgname}}' state=present

